config/routes.rb
Orangeginger::Application.routes.draw do
  resources :tweets

  resources :searches

   root 'tweets#index'

end

app/models/search.rb
# class Search < ActiveRecord::Base
# end

app/models/tweet.rb
class Tweet
  include Mongoid::Document
  #include Mongoid::Search
  #include Mongoid::FullTextSearch
  field :tweetdata, type: String

  #search_in :tweetdata
  #fulltext_search_in :tweetdata

 #  def self.search(search)
	#   	if search
	#     	find(:all, :conditions => ['tweetdata LIKE ?', "%#{search}%"])
	#   	else
	#    	 	find(:all)
	#   	end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # # GET /searches
  # # GET /searches.json
  # def index
  #   @searches = Search.all
  # end

  # # GET /searches/1
  # # GET /searches/1.json
  # def show
  # end

  # # GET /searches/new
  # def new
  #   @search = Search.new
  # end

  # # GET /searches/1/edit
  # def edit
  # end

  # # POST /searches
  # # POST /searches.json
  # def create
  #   @search = Search.new(search_params)

  #   respond_to do |format|
  #     if @search.save
  #       format.html { redirect_to @search, notice: 'Search was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @search }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @search.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /searches/1
  # # PATCH/PUT /searches/1.json
  # def update
  #   respond_to do |format|
  #     if @search.update(search_params)
  #       format.html { redirect_to @search, notice: 'Search was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @search.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /searches/1
  # # DELETE /searches/1.json
  # def destroy
  #   @search.destroy
  #   respond_to do |format|
  #     format.html { redirect_to searches_url }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_search
  #     @search = Search.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def search_params
  #     params.require(:search).permit(:name)
  #   end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    #@tweets = Tweet.all.limit(40)
    #@tweets = Tweet.full_text_search(params[:search]).all.limit(40)
    #@tweets =  Tweet.with(database: "text").mongo_session.command({:tweetdata => {:search => params[:search]}})
    #@tweets =  Tweet.where(tweetdata: {:search => params[:search]}).all
    @tweets = Tweet.all.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweetdata)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'GingerClove', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <main role="main">
           <%= render 'layouts/messages' %>
           <%= yield %>
        </main>
      </div>
    </main>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%# @searches.each do |search| %>
      <tr>
        <td><%#= search.name %></td>
        <td><%#= link_to 'Show', search %></td>
        <td><%#= link_to 'Edit', edit_search_path(search) %></td>
        <td><%#= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @search.name %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweetdata %><br>
    <%= f.text_field :tweetdata %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets/Conversations</h1>

<%# form_tag tweets_path, :method => 'get', class: "form-inline" %>
  <p>
    <div class="col-xs-4">
      <%= text_field :search, params[:search], class: "", :placeholder => "Search" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
    </div>
  </p>
<%# end %>
<br>
<table>
  <thead>
    <tr>
      <th>Tweets count = <%= @tweets.count %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <br>
  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweetdata %></td>
        <td><%#= link_to 'Show', tweet %></td>
        <td><%#= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%#= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @tweets, :container => false %>
  </div>
<%#= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweetdata:</strong>
  <%= @tweet.tweetdata %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>